apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_PASSWORD: YWtoaWwxMjM0NTY=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmFraGlsMTIzNDU2QGxtcy1kYi5jNW1jczBxbzBtY3UudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvbG1zZGI=

